# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Modern Pre Order"
client_id = "e2f917273995ea9e32bafc0a847352c1"
application_url = "https://disc-bathrooms-surveys-complicated.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://disc-bathrooms-surveys-complicated.trycloudflare.com/auth/callback",
  "https://disc-bathrooms-surveys-complicated.trycloudflare.com/auth/shopify/callback",
  "https://disc-bathrooms-surveys-complicated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "starterdq.myshopify.com"
